import type { Metadata } from "next";
import { Geist, Geist_Mono, Limelight, Bokor } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const bokor = Bokor({
  variable: "--font-bokor",
  weight: "400",

  subsets: ["latin"],
});
const limelight = Limelight({
  variable: "--font-lime",
  weight: "400",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Barber",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${limelight.variable} ${bokor.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
