import type { Metadata } from "next";
import {
  limelight,
  ballet,
  geistMono,
  geistSans,
  bokor,
  diplomata,
} from "@/ui/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Barber",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${limelight.variable} ${ballet.variable} ${geistMono.variable} ${diplomata.variable} ${bokor.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
